### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Paptoos** [hascal/hascal#10]
hascal is now to use ?
we can use old versions ? how ?

**Comment by hasan-kashi** [comment]
Hascal has not yet reached the publishing stage.you can use v1.1,this version(v1.1) only work on windows.download v1.1 :
[Download v1.1](http://s14.picofile.com/d/8408588184/81eb93b6-a666-4cc3-90c3-7b7488bafd28/Hascal_SDK.exe)

feature of v1.1 : 
- int , string variable
- if ... else
- while and for loop
- print , sleep , ReadStr,ReadInt built-in function


A new version will be released soon
