### ISSUE TITLE
Old syntax

### ISSUE THREAD

**Issue by mehanalavimajd** [hascal/hascal#12]
Hi to all of the hascal contributions. 
This language syntax is very same as c programming language. 
I think if this language wants to be better you have to change syntax. 
I mean no more semicolon at the end of line or no more int and string variables.
I think It's better make this language syntax like python because python syntax is very easy but c syntax a little hard

**Comment by hasan-kashi** [comment]
Hi.
The goal of Hascal language is power and speed along with easy syntax. Python have an easy syntax but it is very slow due to the dynamics of its variables. we are testing a feature  until the no need to mention the type of variable, so syntax will be easier.
