### ISSUE TITLE
suggestion : Any plans for GUI?

### ISSUE THREAD

**Issue by alirezaahani** [hascal/hascal#18]
I know Hascal is still in beta but will there be a plan for a simple library for making GUIs?

For example, the tk gui toolkit could be included in the standard library of hascal?

**Comment by amirghazi87** [comment]
Tk can be a other library in hascal . not in standard library

**Comment by hasan-kashi** [comment]
> 
> 
> I know Hascal is still in beta but will there be a plan for a simple library for making GUIs?
> 
> For example, the tk gui toolkit could be included in the standard library of hascal?

We are trying to write a simple gui library with sdl
