### ISSUE TITLE
Import libraries without string 

### ISSUE THREAD

**Issue by amirghazi87** [hascal/hascal#21]
like : 
```
use "hascal.core";
```
it is better : 
```
use hascal.core;
```

**Comment by hasan-kashi** [comment]
> 
> 
> like :
> 
> ```
> use "hascal.core";
> ```
> 
> it is better :
> 
> ```
> use hascal.core;
> ```
Yes.it's better.I will change it

**Comment by amirghazi87** [comment]
Thanks

**Comment by hasan-kashi** [comment]
new import syntax added with[ this commit](https://github.com/hascal/hascal/commit/11e04ae3ec1b93d2a4a3e31ab36146d4de519040)
