### ISSUE TITLE
Error running the file

### ISSUE THREAD

**Issue by pranavbaburaj** [hascal/hascal#22]
**Error running the file**
I encountered an error while running the .has file

**Screenshots**
![error](https://raw.githubusercontent.com/pranavbaburaj/pranavbaburaj/error-hascel/rsz_screenshot_581.png)

**Comment by hasan-kashi** [comment]
Create a environment variable with name 'HPATH' and add your hascal compiler to HPATH.

**Comment by pranavbaburaj** [comment]
Ok, Thank you
