### ISSUE TITLE
Improve the language documentation

### ISSUE THREAD

**Issue by pranavbaburaj** [hascal/hascal#23]
## Improve the language documentation
The `hascal` language documentation, is not well written.
It has a lot of confusion with installing it and running it.

## Relative imports
I would also like to know, how to place your `hascal` code on different files
and import them.

# Error messages
The error messages are not understandable.
It just shows `There is an error in your code`

Thank you

**Comment by hasan-kashi** [comment]
Hi.Work in progress.

**Comment by pranavbaburaj** [comment]
I have also added a pull request to hascal/hlm
Please, look into it

https://github.com/hascal/hlm/pull/2
