### ISSUE TITLE
CLI rewrite

### ISSUE THREAD

**Issue by pranavbaburaj** [hascal/hascal#25]
# Hascal CLI

## Reasons for the change
 - The `main` function in the [`hascal.py`](https://github.com/hascal/hascal/blob/main/src/hascal.py) file is cluttered with so many `if..else` statements messing up the code.
 - In this situation, it will be difficult for a new contributor to understand the file
 
 ## Solutions
 - The whole CLI can be rewritten in `click`(or any other CLI library)
 **OR**
 - Create  a separate `ArgumentParser` for parsing the CLI commands

**Comment by hasan-kashi** [comment]
OK,i will change it and .I will use argparse.

**Comment by pranavbaburaj** [comment]
Ok, Thank you
