### ISSUE TITLE
Corrected the pull request

### ISSUE THREAD

**Issue by pranavbaburaj** [hascal/hascal#29]
I have opened a pull request to hascal/hascal - #27

 - Refined the Argument Parser and converted it into a class
 - Added a HascalExecutor class to execute the files

I have corrected the code([as per the instructions](https://github.com/hascal/hascal/pull/27#issuecomment-782826506)).
<br>
Please merge the commits to the `main` branch

Hopefully Pranav Baburaj

**Comment by hasan-kashi** [comment]
Your pull request merged
