### ISSUE TITLE
There is no package named hascal in Ubuntu 20.10

### ISSUE THREAD

**Issue by alirezaahani** [hascal/hascal#3]
I think the title explains the issue.
I tried the command in Hascal's website, but it didn't work.
[The Ubuntu packages website](https://packages.ubuntu.com/search?keywords=hascal&searchon=names&suite=all&section=all)

**Comment by AshkanLaei** [comment]
The hascal language is currently in development.
When it is ready, we put it in the Ubuntu (and other distributions) package manager repositories.
