### ISSUE TITLE
Add let keyword

### ISSUE THREAD

**Issue by pranavbaburaj** [hascal/hascal#36]
- Add some more keywords
    Like the `const` support and using the `let` keyword, etc

- A Project Generator

- A Package Manager(also a website like `[pypi](https://pypi.org) for python`)

I have edited the pull request, Please look into it - #35

**Comment by hasan-kashi** [comment]
Constant is supported in Hascal,`let` keyword will be added.
It is too early to write a project generator for Hascal.

**Comment by hasan-kashi** [comment]
let keyword [added](https://github.com/hascal/hascal/commit/9399d66812571ee96e604616a4826fe4b836d26e).
