### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pranavbaburaj** [hascal/hascal#40]
# **I get bug a bug all the time I run the code**

![BUG](https://raw.githubusercontent.com/pranavbaburaj/pranavbaburaj/main/hascal_issue.png)

I get this error when I run any file in the [examples](https://github.com/hascal/hascal/tree/main/examples) folder, and also the error contains a lot of typos

Please look into this issue 🙂

**Comment by hasan-kashi** [comment]
Please send your code

**Comment by pranavbaburaj** [comment]
The code is the same, I haven't altered anything. I wanted to check the newly written compiler.
So, I just run the file

> NOTE => I haven't altered anything

**Comment by hasan-kashi** [comment]
Is there HPATH ?

**Comment by hasan-kashi** [comment]
Is there HPATH ?

**Comment by pranavbaburaj** [comment]
All the paths are set correctly

**Comment by hasan-kashi** [comment]
I will check this bug.

**Comment by pranavbaburaj** [comment]
OK 🙂 

Should I close this issue???

**Comment by hasan-kashi** [comment]
> OK 🙂
> 
> Should I close this issue???

Don't close this issue.

**Comment by hasan-kashi** [comment]
> 
> # **I get bug a bug all the time I run the code**
> 
> ![BUG](https://raw.githubusercontent.com/pranavbaburaj/pranavbaburaj/main/hascal_issue.png)
> 
> I get this error when I run any file in the [examples](https://github.com/hascal/hascal/tree/main/examples) folder, and also the error contains a lot of typos
> 
> Please look into this issue slightly_smiling_face

This is not a bug .I guess the HPATH variable is not set correctly,reset your HPATH variable value.
