### ISSUE TITLE
Error while installing in linux

### ISSUE THREAD

**Issue by amirghazi87** [hascal/hascal#43]
**Describe the bug**
I have error when i use pyinstaller and create hascal executable file
when i use hascal and run a test code like this : `print("what is your name ?");`
but when i run using `./hascal test.has` i have this error : 
```
Traceback (most recent call last):
  File "hascal.py", line 12, in <module>
  File "core/h_builder.py", line 60, in __init__
  File "core/h_builder.py", line 80, in compile
  File "core/h_compiler.py", line 48, in generate
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[8786] Failed to execute script hascal
```
i installed dmd and using pyinstaller
dmd command works
but i think this bug is because dmd 

**Info**
 - OS: Linux Mint 20.01
 - Python : 3.8.5
 - Hascal : 1.2.5

**Comment by hasan-kashi** [comment]
Sorry,use this stable source : [source](https://github.com/hascal/hascal/releases/tag/v1.2.5.8).

**Comment by pranavbaburaj** [comment]
```sh
export HPATH=<the path of the library>
```
