### ISSUE TITLE
Str or int

### ISSUE THREAD

**Issue by Paptoos** [hascal/hascal#9]
You can Add it to your languege
var name = str;
Or this
var str name;

**Comment by hasan-kashi** [comment]
This is a good suggestion. But the var keyword should be removed.

**Comment by Paptoos** [comment]
name = str
It is Correct ?

**Comment by hasan-kashi** [comment]
no.
`str name;`

We will implement your proposal in the new version of Hascal

**Comment by hasan-kashi** [comment]
I meant:
`str name = "";`

But it is better to change it this way:
`var name = str;`

**Comment by Paptoos** [comment]
`var name = str;`
It is beter , Beacuse later in your programm you can change it

**Comment by hasan-kashi** [comment]
ok
